#!/usr/bin/env python3
"""Regenerate src/app/teaching/experiments/berlin-kay/chips.ts from the World
Color Survey chip colorimetry file.

Source data: `cnum-vhcm-lab-new.txt` from the WCS data archive
(www1.icsi.berkeley.edu/wcs/data.html; mirrored in the jvosten/wcs GitHub
repo at data-raw/cnum-vhcm-lab-new.txt). Columns: chip number, value row
letter (A-J), hue column (0-40), chroma, Munsell hue, Munsell value, and
CIELAB L* a* b* measured under illuminant C.

Conversion: Lab -> XYZ against the illuminant C white point, Bradford
chromatic adaptation C -> D65, XYZ -> linear sRGB -> sRGB transfer -> 8-bit,
with out-of-gamut channels clipped (86 of 330 chips clip; the participant
debrief discloses this).

Usage: python3 scripts/generate-berlin-kay-chips.py path/to/cnum-vhcm-lab-new.txt
"""

import sys

WC = (0.98074, 1.0, 1.18232)  # illuminant C white
WD65 = (0.95047, 1.0, 1.08883)

M = [[0.8951, 0.2664, -0.1614], [-0.7502, 1.7135, 0.0367], [0.0389, -0.0685, 1.0296]]
MI = [
    [0.9869929, -0.1470543, 0.1599627],
    [0.4323053, 0.5183603, 0.0492912],
    [-0.0085287, 0.0400428, 0.9684867],
]
SR = [
    [3.2404542, -1.5371385, -0.4985314],
    [-0.9692660, 1.8760108, 0.0415560],
    [0.0556434, -0.2040259, 1.0572252],
]


def mul(m, v):
    return tuple(sum(m[i][j] * v[j] for j in range(3)) for i in range(3))


def lab_to_xyz(L, a, b, wp):
    fy = (L + 16) / 116
    fx = fy + a / 500
    fz = fy - b / 200

    def inv(t):
        return t**3 if t**3 > 0.008856 else (t - 16 / 116) / 7.787

    return (inv(fx) * wp[0], inv(fy) * wp[1], inv(fz) * wp[2])


def gamma(u):
    u = max(0.0, min(1.0, u))
    return 12.92 * u if u <= 0.0031308 else 1.055 * (u ** (1 / 2.4)) - 0.055


def main(path):
    cs, cd = mul(M, WC), mul(M, WD65)
    scale = [cd[i] / cs[i] for i in range(3)]

    def adapt(xyz):
        lms = mul(M, xyz)
        return mul(MI, tuple(lms[i] * scale[i] for i in range(3)))

    rows = []
    with open(path) as f:
        f.readline()
        for line in f:
            p = line.rstrip("\n").split("\t")
            rows.append(
                (int(p[0]), p[1], int(p[2]), p[4], p[5], float(p[6]), float(p[7]), float(p[8]))
            )
    assert len(rows) == 330, f"expected 330 chips, got {len(rows)}"

    out = []
    clipped = 0
    for cnum, V, H, MunH, MunV, L, a, b in rows:
        lin = mul(SR, adapt(lab_to_xyz(L, a, b, WC)))
        if any(u < -0.005 or u > 1.005 for u in lin):
            clipped += 1
        r, g, bl = (round(gamma(u) * 255) for u in lin)
        out.append((cnum, V, H, f"{MunH} {MunV}", f"#{r:02X}{g:02X}{bl:02X}"))
    out.sort(key=lambda t: t[0])
    print(f"chips: {len(out)}, outside sRGB gamut (clipped): {clipped}")

    lines = [
        "/** The World Color Survey stimulus palette: 330 Munsell chips — 320 chromatic",
        " * (rows B–I x hue columns 1–40, all at maximum available chroma) plus a",
        " * 10-step neutral (value) column 0 running white (A) to black (J). This is the",
        " * same chart Berlin & Kay (1969) used for the focal-chip and boundary-mapping",
        " * procedure, and the chart Nat's earlier PP3LAN classes annotated by hand.",
        " *",
        " * Colorimetry: chip L*a*b* values are from the WCS data archive file",
        " * `cnum-vhcm-lab-new.txt` (measured under illuminant C). Conversion here:",
        " * Lab -> XYZ (illuminant C white) -> Bradford adaptation to D65 -> linear",
        " * sRGB -> sRGB transfer -> 8-bit, out-of-gamut channels clipped. Roughly a",
        " * quarter of the high-chroma chips exceed the sRGB gamut and are clipped",
        " * toward less saturated values — the debrief says so: an sRGB monitor",
        " * cannot show a Munsell book, and that is itself a teaching point.",
        " * Generated by scripts/generate-berlin-kay-chips.py; do not hand-edit. */",
        "",
        "export interface Chip {",
        "  /** WCS chip number, 1-330 — the stable id used in submissions. */",
        "  cnum: number;",
        "  /** Lightness row A (white) to J (black); chromatic chips span B-I. */",
        "  row: string;",
        "  /** Hue column 1-40; 0 is the neutral column. */",
        "  col: number;",
        '  /** Munsell hue + value notation, e.g. "5.0R 4". */',
        "  munsell: string;",
        "  hex: string;",
        "}",
        "",
        'export const ROWS = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"] as const;',
        "",
        "export const CHIPS: Chip[] = [",
    ]
    for cnum, V, H, mun, hexv in out:
        lines.append(
            f'  {{ cnum: {cnum}, row: "{V}", col: {H}, munsell: "{mun}", hex: "{hexv}" }},'
        )
    lines.append("];\n")
    lines.append(
        "/** Grid lookup: byGrid[row][col] -> Chip (rows A and J exist only at col 0). */"
    )
    lines.append("export const byGrid: Record<string, Record<number, Chip>> = {};")
    lines.append("for (const c of CHIPS) {")
    lines.append("  (byGrid[c.row] ??= {})[c.col] = c;")
    lines.append("}")
    lines.append("")
    lines.append("export const byCnum: Record<number, Chip> = {};")
    lines.append("for (const c of CHIPS) byCnum[c.cnum] = c;")
    lines.append("")

    dest = "src/app/teaching/experiments/berlin-kay/chips.ts"
    with open(dest, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {dest}")


if __name__ == "__main__":
    main(sys.argv[1])
